version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo Running tests...
      # Add commands to run your tests here (if any)

  build:
    commands:
      - ls
      - echo Building Lambda function 1...
      - cd lambda_functions/lf1
      - zip -r ../lambda_function_1.zip *
      - aws s3 cp ../lambda_function_1.zip s3://b1cdpipe
      - cd ../lf2
      - zip -r ../lambda_function_2.zip *
      - aws s3 cp ../lambda_function_2.zip s3://b1cdpipe
      - cd ../lf3
      - zip -r ../lambda_function_3.zip *
      - aws s3 cp ../lambda_function_3.zip s3://b1cdpipe

  post_build:
    commands:
      - echo Updating Lambda functions...
      - aws lambda update-function-code --function-name lf1 --s3-bucket b1cdpipe --s3-key lambda_function_1.zip
      - aws lambda update-function-code --function-name lf2 --s3-bucket b1cdpipe --s3-key lambda_function_2.zip
      - aws lambda update-function-code --function-name lf3 --s3-bucket b1cdpipe --s3-key lambda_function_3.zip